- hosts: 127.0.0.1
  connection: local
  become: 'yes'
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: true
    - name: install node 
      shell: |
       curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - && sudo apt-get install -y nodejs
      
